services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: jnhbgvfc
      POSTGRES_DB: tasty-recipe
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    networks:
      - postgresql
    volumes:
      - postgresql-volume:/postgres

networks:
  postgresql:
volumes:
  postgresql-volume: